### ISSUE TITLE
Unable to connect using MySql5.7 and Node18 / Node 19

### ISSUE THREAD

**Issue by prodoxx** [sidorares/node-mysql2#1890] opened 2023-03-13 05:38 UTC
When using MySql2 with a MySql5.7 instance and also using either Node 18 or Node 19, I'm unable to connect to the database.

### How to reproduce:

**Spin up mysql 5.7 docker container**
```
docker pull mysql:5.7
docker run --name mysql5 -p 3306:3306 -v mysql_volume:/var/lib/mysql/ -d -e "MYSQL_ROOT_PASSWORD=pass" mysql:5.7
```

**Change Node 19 using [NVM](https://github.com/nvm-sh/nvm)**
```
nvm install 19.5.0
nvm use 19.5.0
```

Run the following (change db credentials & create a test_db database):
```typescript
// get the client
import mysql from 'mysql2';

// create the connection to database
const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: 'pass',
  database: 'test_db'
});

console.log('Authorized: ', connection.authorized);
```

### Current behavior 

```
Authorized: false
```

### Expected behavior 

```
Authorized: true
```

**Comment by sidorares** [comment] 2023-03-13 05:43
Are you sure it fails to connect? Your console.log runs before any communication is done, try to change to below:

```js
const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: 'pass',
  database: 'test_db'
}).on('error', err => {
  console.log('Connection error:', err);
}).on('connect', () => {
  console.log('Authorized: ', connection.authorized);
});
```

**Comment by prodoxx** [comment] 2023-03-13 06:01
💯 , it fails to connect. 

Changed to the code you suggested and tried again.
Results using Node 19.5.0:
```
test-mysql2  nvm use 19.5.0
Now using node v19.5.0 (npm v9.3.1)
➜  test-mysql2  ts-node index.ts
Connection error: Error: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 3306,
  fatal: true
}
```

Using Node 18:
```
test-mysql2  nvm use 18 
Now using node v18.15.0 (npm v9.5.0)
➜  test-mysql2  pnpm i
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
➜  test-mysql2  ts-node index.ts
Connection error: Error: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 3306,
  fatal: true
}
```
Using node 16:
```
test-mysql2  nvm use 16
Now using node v16.19.0 (npm v8.19.3)
➜  test-mysql2  pnpm i
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
➜  test-mysql2  ts-node index.ts
Authorized:  true
```

**Comment by sidorares** [comment] 2023-03-13 06:15
Change 'localhost' to '127.0.0.1', your mysql server listens on ipv4 address only and node 19 resolves localhost into ipv6 address `::1`

possibly a duplicate of #1668 and #1840

**Comment by sidorares** [comment] 2023-03-13 06:16
https://github.com/nodejs/node/issues/40537

**Comment by prodoxx** [comment] 2023-03-13 06:43
@sidorares , that fixed the problem. Thanks a ton, I was scratching my head on this problem all morning. And thanks for this great package.

**Closed** 2023-03-13 06:43 UTC
