### ISSUE TITLE
mysql2 driver does not respect timeout option on the query

### ISSUE THREAD

**Issue by arupadhy** [sidorares/node-mysql2#789] opened 2018-05-30 15:17 UTC
mysql2 does not seem to have similar api contract as mysql.For a use case, where we want to timeout a query (kill the query and free resources on database end).
mysql seems to support "timeout" .
con.query({sql: <>, values: <>, timeout: <>}, cb);

mysql2 does not seem to respect timeout option...As per documentation, it states everything available via mysql apis should be supported

version of mysql2: 1.5.3

**Comment by sidorares** [comment] 2018-05-31 00:55
@arupadhy we don't promise 100% compatibility, though it's high on priority. Two projects add features at different time and over time we try to synchronise them. The only really shared code is parameter placeholders ( via https://npmjs.org/package/sqlstring ), also bits of pool and connection config code were cherry-picked about 3 years ago. Other than that code base is independent and while we want to have migration both ways mysql <-> mysql2 to be easy some differences are inevitable


Note that mysqljs/mysql query timeout is client side code and does not kill long running query on the server. 

Closing this issue as duplicate of #185

**Closed by sidorares** 2018-05-31 00:55 UTC
