### ISSUE TITLE
Need mysql2 support Timeout on Query

### ISSUE THREAD

**Issue by billnbell** [sidorares/node-mysql2#700] opened 2017-12-24 05:46 UTC
When running queries we want to set a timeout to 1 second. And if the query does not come back in 1 second, we want to abort - know it failed - and go do something else.

We don't care about killing the request in Mysql. We just want it to come back in 1 second.

How do we do this in mysql2?

**Comment by araker** [comment] 2017-12-27 09:25
+1 would be nice to have query based timeouts like in [mysqljs/mysql](https://github.com/mysqljs/mysql#timeouts)

**Comment by billnbell** [comment] 2018-01-25 23:03
so who can work on it? how do we handle timeouts on execute() or query()

**Comment by martinhj** [comment] 2018-03-08 08:42
A question connected to this (and depending on the answer maybe an argument for a feature like this):

**Comment by martinhj** [comment] 2018-03-08 08:50
@sidorares: A question connected to the timeout vs a sleep()-method you describe (and depending on the answer maybe an argument for a timeout feature):

With a solution like you are stipulating, wouldn't the query potentially go through even though it times out? I guess that makes it more difficult to abstract programs interacting with a database if one need to take into account that a query might go through even though the flow of your program reflects something else?

(I'm using the node-mysql2/promises-wrapper and since es6' promises isn't cancelable it isn't a straight forward to cancel it either?)

**Comment by sidorares** [comment] 2018-03-08 09:19
@martinhj yes, the query will still go, there is no easy way to cancel query once it was started. You could kill connection completely and throw it away, or from another connection actually interrupt query in the first one using `KILL` query - https://dev.mysql.com/doc/refman/5.7/en/kill.html

Note that because we queue queries on a connection it might be useful to add some api to express "if this query sits X amount of time before even being sent to server - don't bother and discard it" (this is currently not easy to achieve)

**Comment by martinhj** [comment] 2018-03-08 09:35
@sidorares ok, thank you!

**Comment by sidorares** [comment] 2018-05-31 00:54
closing this as duplicate of #185 , trying to consolidate into one issue

**Closed by sidorares** 2018-05-31 00:54 UTC
