### ISSUE TITLE
Typing issue: connection.promise() method is not present in typescript definition files

### ISSUE THREAD

**Issue by hauboldj** [sidorares/node-mysql2#1860] opened 2023-02-24 20:19 UTC
Using typescript the `promise` method is not present on the connection object. See the following error.
```
import mysql from 'mysql2'
const targetConnection = mysql.createConnection(config.targetConnection)
targetConnection.promise()
```
![image](https://user-images.githubusercontent.com/2679742/221274881-9f62612d-6b8c-49fa-934f-7574273d3aba.png)

If I set the type of the connection to `any` then the code compiles and executes without any issues (but this isn't ideal from a typescript perspective).
e.g.
```
import mysql from 'mysql2'
const targetConnection:any = mysql.createConnection(config.targetConnection)
targetConnection.promise()
```
I believe this issue is because the [`typings` property](https://github.com/sidorares/node-mysql2/blob/master/package.json#L9) in package.json points to the mysql typings not `index.d.ts`

**Comment by sidorares** [comment] 2023-02-27 04:00
duplicate of #1816 
I'm closing this one, please use liked issue to track

**Closed by sidorares** 2023-02-27 04:00 UTC
