### ISSUE TITLE
 Bind parameters must not contain undefined. To pass SQL NULL specify JS null

### ISSUE THREAD

**Issue by Kavindu95** [sidorares/node-mysql2#2321] opened 2023-12-20 02:50 UTC
/home/kavindu/Documents/dep-11/final-phase/nodejs/projects/todo-app-backend/node_modules/mysql2/lib/connection.js:661
          throw new TypeError(
                ^

TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /home/kavindu/Documents/dep-11/final-phase/nodejs/projects/todo-app-backend/node_modules/mysql2/lib/connection.js:661:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (/home/kavindu/Documents/dep-11/final-phase/nodejs/projects/todo-app-backend/node_modules/mysql2/lib/connection.js:653:22)
    at /home/kavindu/Documents/dep-11/final-phase/nodejs/projects/todo-app-backend/node_modules/mysql2/promise.js:121:11
    at new Promise (<anonymous>)
    at PromisePoolConnection.execute (/home/kavindu/Documents/dep-11/final-phase/nodejs/projects/todo-app-backend/node_modules/mysql2/promise.js:118:12)
    at getAllTask (/home/kavindu/Documents/dep-11/final-phase/nodejs/projects/todo-app-backend/src/controller/task.http.controller.ts:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
![Screenshot from 2023-12-20 08-18-59](https://github.com/sidorares/node-mysql2/assets/115790355/af1ac7fe-b247-4b67-9e63-ce04a8833170)

create method is wornking but other handler methods are not working ? can you help me anyone

**Comment by wellwelwel** [comment] 2023-12-20 02:54
Hi @Kavindu95, can you share an example of the code (your query) that is returning this error?

**Comment by Kavindu95** [comment] 2023-12-20 03:04
`import {Router} from "express";
import {Request,Response} from "express-serve-static-core";
import mysql, {ResultSetHeader, RowDataPacket} from 'mysql2/promise';
import {TaskTo} from "../to/task.to.js";
import 'dotenv/config';

const controller=Router();

controller.get('/', getAllTask);


controller.post('/', saveTask);


controller.patch('/:id', updateTask);


controller.delete('/:id', deleteTask);

export {controller as TaskHttpController};

const pool=mysql.createPool({
    database: process.env.DB_NAME,
    port: +process.env.DB_PORT!,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST,
    connectionLimit: +process.env.DB_CONNECTION_LIMIT!

});


async function getAllTask(req: Request,res: Response){

    if (req.query.email) res.sendStatus(400);
    const connection = await pool.getConnection();
    const [taskList] = await connection.execute('SELECT * FROM tasks WHERE email = ?', [req.query.email]);
    res.json(taskList);
    pool.releaseConnection(connection);

}
async function saveTask(req:Request,res:Response){
    const task = <TaskTo>req.body;
    const connection = await pool.getConnection();
    const [{insertId}] = await connection.execute<ResultSetHeader>('INSERT INTO tasks (description, status, email) VALUES (?, false, ?)', [task.description, task.email]);
    pool.releaseConnection(connection);
    task.id = insertId;
    task.status = false;
    res.status(201).json(task);


}

async function updateTask(req:Request, res:Response){
    const taskId = +req.params.id;
    const task = <TaskTo>req.body;
    const connection = await pool.getConnection();
    const [result] = await connection.execute<RowDataPacket[]>('SELECT * FROM tasks WHERE id = ?'[taskId]);
    if (result.length) {
        res.sendStatus(404);
        return;
    }
    else {
        await connection.execute('UPDATE tasks SET description = ?, status = ? WHERE id=?', [task.description, task.status, taskId]);
        res.sendStatus(204);
    }
}

async function deleteTask(req:Request,res:Response){
    const taskId = +req.params.id;
    const task = <TaskTo>req.body;
    const connection = await pool.getConnection();
    const [result] = await connection.execute<RowDataPacket[]>('SELECT * FROM tasks WHERE id = ?'[taskId]);
    if (!result.length) {
        res.sendStatus(404);
        return;
    }
    else {
        await connection.execute('DELETE FROM tasks WHERE id=?', [taskId]);
        res.sendStatus(204);
    }
}

`

**Comment by Kavindu95** [comment] 2023-12-20 03:06
That is my .env file
====================
DB_HOST=localhost
DB_PORT=3306
DB_NAME=dep11_todo_app
DB_USER=root
DB_PASSWORD=7788
DB_CONNECTION_LIMIT=10

**Comment by Kavindu95** [comment] 2023-12-20 03:06
That is my TaskTo file
======================
export class TaskTo{
    constructor(public  id:number,
                public description:string,
                public status:boolean,
                public email:string) {

    }
}

**Comment by wellwelwel** [comment] 2023-12-20 04:16
I believe that the problem is occurring in `const task = req.body`, because the server doesn't seem to parse the `body`.

Following your example in a simple way:

> See the comments 🕵🏻

```ts
import express, { Router } from 'express';
import mysql, { ResultSetHeader } from 'mysql2/promise';

// 1. Importing the body parser
import bodyParser from 'body-parser';

const pool = mysql.createPool({
   host: 'localhost',
   user: 'root',
   database: 'test',
});

const server = express();
const router = Router();

// 2. Request parser
server.use(bodyParser.json());

router.post('/', async (req, res) => {
   const conn = await pool.getConnection();
   const task = req.body;

   const [{ insertId }] = await conn.execute<ResultSetHeader>(
      'INSERT INTO tasks (description, status, email) VALUES (?, false, ?)',
      [task.description, task.email]
   );

   conn.release();

   res.status(201).json(insertId);
});

server.use(router);

server.listen(3000);
```

---

@Kavindu95, can you try using `body-parser`?

**Comment by wellwelwel** [comment] 2023-12-20 04:23
You can also check the `task` output.

```js
const task = req.body;

console.log(task);
```

---

Reproducing your error without the server would be like:

```ts
 const [{ insertId }] = await conn.execute<ResultSetHeader>(
    'INSERT INTO tasks (description, status, email) VALUES (?, false, ?)',
    [undefined, undefined]
 );
```

**Comment by wellwelwel** [comment] 2023-12-20 04:40
Wait... I assumed you were referring to creation (`saveTask`) because of the image 😂

Your problem is here?
```ts
if (req.query.email) res.sendStatus(400);
const connection = await pool.getConnection();
const [taskList] = await connection.execute('SELECT * FROM tasks WHERE email = ?', [req.query.email]);
res.json(taskList);
pool.releaseConnection(connection);
```

If yes, you can do it:
```ts
if (req.query.email) {
  res.sendStatus(400);
  return;
}

const connection = await pool.getConnection();
const [taskList] = await connection.execute('SELECT * FROM tasks WHERE email = ?', [req.query.email]);
res.json(taskList);
pool.releaseConnection(connection);
```

**Comment by wellwelwel** [comment] 2024-01-11 21:32
I'm closing this Issue, but feel free to reopen it and ask anything 🙋🏻‍♂️

**Closed by wellwelwel** 2024-01-11 21:32 UTC
