### ISSUE TITLE
HANDSHAKE_SSL_ERROR with RDS and 3.9.3+

### ISSUE THREAD

**Issue by mattmbrightside** [sidorares/node-mysql2#2581] opened 2024-04-09 15:54 UTC
using mysql2 with AWS nodejs lambdas and AWS RDS.

As of March 2024, our RDS instance was still on the 2019 certificate bundle.  Versions of mysql2 <3.9.3 were working fine with calls to createConnection.  We updated a project to 3.9.3 and started getting these errors:

{"errorType":"Error","errorMessage":"unable to get local issuer certificate","code":"HANDSHAKE_SSL_ERROR","message":"unable to get local issuer certificate","stack":["Error: unable to get local issuer certificate","    at fn (/private/var/folders/48/8n9w9qzn17s1gpq7tjs3cnv40000gp/T/tmplakzpggq/node_modules/mysql2/promise.js:253:31)

I noticed the reference to https://github.com/sidorares/node-mysql2/pull/2131 and instructed my team to update the mysql certificate bundle so we could retest.  We updated RDS to bundle rds-ca-rsa2048-g1.   Trying mysql2 3.9.3 gives the same error.

I noticed the mysql2 issue: https://github.com/sidorares/node-mysql2/pull/2542 regarding the certificates and waited for the fix and for 3.9.4.  We have tried again with 3.9.4 and get the same error on calls to createConnection.

If anyone is successfully using this package 3.9.3 or 3.9.4 with RDS, please let me know what steps are required to get past this error.  Thanks!

**Comment by mattmbrightside** [comment] 2024-04-09 16:16
a bit more info, we are using the AWS RDS Proxy service between the lambda and RDS and our connection options passed to createConnection are
{
  "host": "<rds proxy>.<region>.rds.amazonaws.com",
  "user": "username",
  "password": "password",
  "database": "dbname",
  "ssl": "Amazon RDS",
  "charset": "utf8mb4"
}

**Comment by wellwelwel** [comment] 2024-04-09 19:50
Thanks, @mattmbrightside. That clarifies things 🙋🏻‍♂️
This issue can be fixed by joining old and new certificates, but this will create an even larger file.

Unfortunately, even with a **RDS** in hand, I wouldn't be able to reproduce this error, since it will be created with one of the new certificates.

---

@sidorares, I think it's important to move this responsibility to a separate dependency soon for more flexibility. Users will soon be alerted to update to version **3.9.4**.

**Comment by jeffrey-mutual** [comment] 2024-04-10 00:01
I would love to help reproduce this error (and create a PR with a fix), but I seem to be having some difficulty doing so.

Amazon RDS
MySQL version 8.0.35
Certificate authority is rds-ca-2019
mysql2@3.9.4

Config is
```
{
  host: '<name>.rds.amazonaws.com',
  database: 'db',
  user: 'user',
  password: 'password',
  ssl: 'Amazon RDS'
}
```

This works fine and I'm able to query the database through mysql2. Anything else you'd like me to check?

**Comment by sidorares** [comment] 2024-04-10 01:39
@wellwelwel I created https://github.com/mysqljs/aws-ssl-profiles and added you as a maintainer

Intended use when it's ready would be something along the lines

```js
import awsCaBundle from 'aws-ssl-profiles';

const connection = mysql.createConnection({
  //...
  ssl: awsCaBundle
})l

```

**Comment by dougwilson** [comment] 2024-04-10 02:33
If only RDS would have just used public certificates like Azure 🤦‍♂️

**Comment by wellwelwel** [comment] 2024-04-10 02:58
> @sidorares
> cc: @dougwilson

I tried something manually that I find interesting:

- New feature behavior with current usage:

```js
import mysql from 'mysql2';

const connection = mysql.createConnection({
  // Load all certificates (old + new) internally using "aws-ssl-profiles"
  // We can document this usage as @deprecated
  ssl: 'Amazon RDS'
});
```

- New feature usage behavior for legacy certs:

```js
import mysql from 'mysql2';
import { legacyRDS } from 'aws-ssl-profiles';

const connection = mysql.createConnection({
  // Load only old certificates
  ssl: legacyRDS,
});
```

- New feature usage behavior for new certs:

```js
import mysql from 'mysql2';
import { RDS } from 'aws-ssl-profiles';

const connection = mysql.createConnection({
  // Load only new certificates
  ssl: RDS,
});
```

> By this way, it would be a "normal" `feat:` instead of a `feat!:`.

---

If it's not a problem, I'd like to develop it using **TypeScript**, instead of a manual `index.d.ts` 🧙🏻

---

What do you think? 🙋🏻‍♂️

**Comment by wellwelwel** [comment] 2024-04-10 03:16
> Just to illustrate 💡

In _lib/constants/ssl_profiles.js_, it would be something like:

```js
const { legacyRDS, RDS } = require('aws-ssl-profiles');

exports['Amazon RDS'] = {
  ca: [...legacyRDS, ...RDS],
}
```

**Comment by wellwelwel** [comment] 2024-04-10 03:54
Really thanks, @mattmbrightside 🤝

When looking into https://github.com/sidorares/node-mysql2/pull/2131/commits/675dd0411017053375a18248c38a2b8b55de24ed, it's possible to see that not all old certificates have been removed, which would explain why only some servers return the authentication error.

**Comment by jeffrey-mutual** [comment] 2024-04-10 07:22
> Really thanks, @jeffrey-mutual 🤝
> 
> When looking into [675dd04](https://github.com/sidorares/node-mysql2/commit/675dd0411017053375a18248c38a2b8b55de24ed), it's possible to see that not all old certificates have been changed, which would explain why only some servers return the authentication error.

I guess I got lucky then. Both of my databases work on 3.9.4. Without a repro I probably won't work on the PR since I wouldn't easily be able to validate the fix.

**Comment by EasyKoen** [comment] 2024-04-16 14:56
We have the same issue, we also use RDS Proxy.

I found the following information from AWS: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.howitworks.html#rds-proxy-security.tls:

_When using a client with --ssl-mode VERIFY_CA or VERIFY_IDENTITY, specify the --ssl-ca option pointing to a CA in .pem format. For the .pem file to use, download all root CA PEMs from [Amazon Trust Services ](https://www.amazontrust.com/repository/) and place them into a single .pem file._

https://www.amazontrust.com/repository/ has 5 root CA's, I am going to add them manually to our setup and see if that resolves the problem.

**Comment by EasyKoen** [comment] 2024-04-16 15:00
Well, that actually did the trick. 

So there you have it. When you connect to RDS through RDS Proxy, you need the Amazon Root CA's which you can find on the website I posted in the comment above.

**Comment by pedrovanzella** [comment] 2024-04-24 15:32
I can also confirm that adding those certs to the certificate chain fixes the issues for me, using RDS Proxy. Maybe they can just be added to the chain in this repo while the certificates package isn't done yet?

**Comment by arturjeber** [comment] 2024-04-28 14:52
Same problem with Azure when using Nextjs 14

const dbConfig = {
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  ssl: { 
     cert:  process.env.DB_SSL.replace(/\\n/g, '\n')
  },
};

{
  status: 401,
  results: [],
  error: [Error: 00417A49F87F0000:error:0A00010B:SSL routines:tls_validate_record_header:wrong version number:ssl/record/methods/tlsany_meth.c:81:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'HANDSHAKE_SSL_ERROR',
    fatal: true
  }
}

**Comment by robert-pitt-foodhub** [comment] 2024-04-29 18:43
![image](https://github.com/sidorares/node-mysql2/assets/70318887/11ed52b7-ddb3-418c-a9c8-9a9a0220016c)

We have updated our version from 3.1.1 to 3.9.7 in our SIT environment and this error was introduced across hundreds of lambdas, we are going to revert back to 3.1.1, but thought I would share here to help confirm that the recent changes in 3.9.7 are failing RDS connections

**Comment by MarioRomanDono** [comment] 2024-07-04 11:13
Hi, we have run into the same issue in our team, and we have been able to solve it without directly including the CA certificate. We have two RDS databases, one for our staging environment and one for production (both use `rds-ca-rsa2048-g1` as CA). For production, we also use RDS proxy to manage connections. In our case, we are able to successfully connect using TLS and the last version of node-mysql2 (3.10.2) with the following options:

- Without using RDS Proxy: `ssl: "Amazon RDS"`. This option includes the CA certificates bundled in https://github.com/sidorares/node-mysql2/blob/f23c0f13d0e3b870c025ee5b2fe21ecff51c2844/lib/constants/ssl_profiles.js#L7
- Using RDS Proxy: `ssl: {}`. As @EasyKoen posted, RDS proxy connection needs Amazon root CA certificates, but these are not included in `ssl_profiles.js` (and I believe they are not included in https://github.com/mysqljs/aws-ssl-profiles either). But, if you check the source code of this library, specifically the line where SSL options are used: https://github.com/sidorares/node-mysql2/blob/f23c0f13d0e3b870c025ee5b2fe21ecff51c2844/lib/connection.js#L347 as well as Node documentation for [createSecureContext](https://nodejs.org/docs/latest-v20.x/api/tls.html#tlscreatesecurecontextoptions), if you do not set anything for `ca`, Mozilla CAs list will be used, which already includes Amazon root CA certificates.

Right now I think this can be a little confusing for anyone intending to use RDS proxy with TLS, because there are [no instructions in the documentation](https://sidorares.github.io/node-mysql2/docs/examples/connections/create-connection#createconnectionconfig--rds-ssl) for setting a successful connection. Another alternative, as @pedrovanzella said, would be to include these CA certificates to both `ssl_profiles.js` and `aws-ssl-profiles` package, and always use `ssl: "Amazon RDS"`. I would be happy to help submitting a PR with the solution of your preference, either updating the documentation or the CA files 😄

**Comment by wellwelwel** [comment] 2024-07-04 18:15
Hi, @MarioRomanDono 🙋🏻‍♂️

The `ssl: {}` mentioned removes the `ca` property that includes certificates.

In theory, the issue would be fixed by adding the **AWS Proxy** certificates to the existing certificates in [aws-ssl-profiles](https://github.com/mysqljs/aws-ssl-profiles), then import it to **MySQL2**.

---

Currently the test suite is breaking on some tests after **MySQL Server** `v9`, resolving this, certificates is my next priority, but feel free to contribute first 🚀
 
My idea would be to create the possibility of using the proxy certificates individually (namespace export) and, by default, joining the current certificates to the proxy certificates (default export).

**Closed** 2024-07-15 22:37 UTC
