### ISSUE TITLE
Unknown command: 22

### ISSUE THREAD

**Issue by m1sta** [sidorares/node-mysql2#126] opened 2014-10-02 10:15 UTC
Thank you again for adding authentication support to the server/proxy components of mysql2. I'm now stuck with a new error. Two in fact, which I am guessing are related, although I really don't know. I'm using the MySQL ODBC driver to connect  to query a MySQL server via a node-mysql2 proxy from Microsoft Query (within Microsoft Excel). 

The first problem I'm having, and the lesser important of the two, is that the list of columns isn't returned via the proxy. This appears to be an issue with the `field list` event not returning any valid data. 

The second problem, and the real issue, is that when I enter the query `select * from table1 where (col1 = ?)`. The question mark is used to indicate a parameter within Microsoft Query/Excel. When this query is evaluated the proxy logs `Unknown command: 22` to the console and the client hangs. 

Is there an easy change I can make so that the `field list` and any `unknown command` situations are proxied unchanged through to/from the real MySQL server? 

Perhaps just a packet forward of some kind?

**Comment by sidorares** [comment] 2015-01-09 22:45
closing as duplicate of #127

**Closed by sidorares** 2015-01-09 22:45 UTC
Labels: question, server
