### ISSUE TITLE
Problematic overload definitions for Connection.query()

### ISSUE THREAD

**Issue by sergburn** [sidorares/node-mysql2#1329] opened 2021-06-01 12:03 UTC
Current definition of Connection.query() methods, with 4 overloads, makes it difficult to write a wrapper on top of Connection class:
```typescript
type ResultVariants = RowDataPacket[][] | RowDataPacket[] | OkPacket | OkPacket[] | ResultSetHeader;
type QueryValues = any | any[] | { [param: string]: any };
type SqlResult<T extends ResultVariants> = [T, FieldPacket[]];

query<T extends ResultVariants>(sql: string, values?: QueryValues): Promise<SqlResult<T>>;
query<T extends ResultVariants>(sql: mysql.QueryOptions, values?: QueryValues): Promise<SqlResult<T>>;
query<T extends ResultVariants>(sql: string | mysql.QueryOptions, values?: QueryValues): Promise<SqlResult<T>> {
  return this.connImpl.query(sql, values);
}
```
TSC gives following error:
>  error TS2769: No overload matches this call.
  Overload 1 of 4, '(sql: string, values: any): Promise<[T, FieldPacket[]]>', gave the following error.
    Argument of type 'string | QueryOptions' is not assignable to parameter of type 'string'.
      Type 'QueryOptions' is not assignable to type 'string'.
  Overload 2 of 4, '(options: QueryOptions, values: any): Promise<[T, FieldPacket[]]>', gave the following error.
    Argument of type 'string | QueryOptions' is not assignable to parameter of type 'QueryOptions'.
      Type 'string' is not assignable to type 'QueryOptions'.
   return this.connImpl.query(sql, values);

Same happens even if the wrapper also defines 4 overloads. 

According to [TypeScript Handbook, the better way](https://www.typescriptlang.org/docs/handbook/2/functions.html#writing-good-overloads) to define overloads with the same amount of arguments is to use union types.

Following definitions fixes the problem:
```typescript
  query<T extends RowDataPacket[][] | RowDataPacket[] | OkPacket | OkPacket[] | ResultSetHeader>(
    sql: string | QueryOptions
  ): Promise<[T, FieldPacket[]]>;
  query<T extends RowDataPacket[][] | RowDataPacket[] | OkPacket | OkPacket[] | ResultSetHeader>(
    sql: string | QueryOptions,
    values: any | any[] | { [param: string]: any }
  ): Promise<[T, FieldPacket[]]>;
```

And since `values` is actually optional argument, just single signature should be enough:
```typescript
  query<T extends RowDataPacket[][] | RowDataPacket[] | OkPacket | OkPacket[] | ResultSetHeader>(
    sql: string | QueryOptions,
    values?: any | any[] | { [param: string]: any }
  ): Promise<[T, FieldPacket[]]>;
```

**Comment by vicary** [comment] 2021-06-30 15:35
In fact `RowDataPacket[][] | RowDataPacket[] | OkPacket | OkPacket[] | ResultSetHeader` alone is hard enough to use.

**Comment by sidorares** [comment] 2021-06-30 22:05
Unfortunately this just reflects all possible variations that mysql can return in response to SQL query: insert result, array of rows ( one insert / select ); and also array of insert result | array of rows ( multiple statements in the query or single statement but call to a stored procedure ). See examples in tests: https://github.com/sidorares/node-mysql2/blob/07a429d9765dcbb24af4264654e973847236e0de/test/integration/connection/test-multiple-results.js#L70-L94

If anyone has suggestion to handle this polymorphic mysql behaviour in a better way in the API - feel free to comment ( even if it's backwards incompatible, I'm thinking about releasing a fully incompatible line of driver that has some known api issues removed )

**Comment by vicary** [comment] 2021-06-30 22:27
It is actually unresolvable for string based queries because type inference is not possible.

You'll need some kind of query builder to reduce the possible types.

I think you are onto something, a major release or a new downstream project maybe the only way out.

**Comment by ArtskydJ** [comment] 2023-01-19 21:00
Here's a replication of the problem:
```ts
import type { Connection } from 'mysql2/promise'
import mysql from 'mysql2/promise'

const main = async(connectionOptions) => {
	const connection = await mysql.createConnection(connectionOptions)

	const [ results1 ] = await connection.query('SELECT * FROM COLUMNS')
	console.log(results1)


	const myQueryRunner = (
		...args: Parameters<Connection['query']>
	) => connection.query(...args)


	// TYPESCRIPT ERROR: Expected 2 arguments, but got 1. typescript(2554)
	const [ results2 ] = await myQueryRunner('SELECT * FROM COLUMNS')


	console.log(results2)
}


main({
	host: 'localhost',
	port: 3306,
	user: 'root',
	password: process.env.MYSQL_PASSWORD,
	database: `information_schema`,
}).catch(e => {
	console.error(e)
	process.exit(1)
})
```
![image](https://user-images.githubusercontent.com/1833684/213558545-e8fa0f74-1fc5-4024-a346-eb84ab12c84b.png)

**Comment by wellwelwel** [comment] 2023-07-06 12:05
Hi @ArtskydJ.

In your last example, instead:
```ts
const myQueryRunner = (
  ...args: Parameters<Connection['query']>
) => connection.query(...args)
```

You can use it by reassigning the `query` method like:
```ts
const myQueryRunner = connection.query;
```

Now your code will work 🤹🏻‍♀️

---

Alternatively, if you know the expected results, for example, always be a "normal" `SELECT`, then you can reproduce the same example as follows:
```ts
const myQueryRunner = connection.query<RowDataPacket[]>;
// or the type(s) that best fits your case
```

Now, by using your `myQueryRunner`, it always be a `RowDataPacket[]` type.

**Comment by wellwelwel** [comment] 2023-07-06 12:28
@ArtskydJ, just exemplifying my comment visually 🙋🏻‍♂️

<img width="728" alt="Screenshot 2023-07-06 at 09 27 37" src="https://github.com/sidorares/node-mysql2/assets/46850407/9ad3496d-f0e2-4a4d-8f8c-87a077a68274">

**Comment by wellwelwel** [comment] 2023-07-06 13:37
@sergburn, you don't need to recreate every overload again 🙋🏻‍♂️

To reach the same approach from my example for @ArtskydJ, but using a **class**, you will need to create a `getter method`.
For example:

```ts
import mysql, { Pool } from 'mysql2/promise';

class MySQL {
  private connImpl: Pool;

  constructor(connImpl: Pool) {
    this.connImpl = connImpl;
  }

  get query() {
    return this.connImpl.query;
  }
}

/** Testing */
const pool = mysql.createPool({});
const db = new MySQL(pool);

db.query('');
db.query('', []);
db.query({ sql: '' });
db.query({ sql: '' }, []);

```

**Comment by wellwelwel** [comment] 2023-07-06 13:47
@sidorares, these answers are the reason why I don't see this situation as an issue.

A documented example instructing how to create a basic custom class using **TypeScript** would resolve this discussion.

---

@sergburn and @ArtskydJ, soon these situations will be documented 🙋🏻‍♂️

**Comment by wellwelwel** [comment] 2023-07-09 13:15
You can follow the TypeScript documentation for **Query and Execute** in [documentation/en/TypeScript-Examples.md#query-and-execute](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/TypeScript-Examples.md#query-and-execute).

And the **Type Specification** in [documentation/en/TypeScript-Examples.md#type-specification](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/TypeScript-Examples.md#type-specification).

Here is a basic custom class exposing/extending the `query` and `execute` methods for each type expected:
- [examples/typescript/basic-custom-class.ts](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/basic-custom-class.ts)

---

I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️

**Closed by wellwelwel** 2023-07-09 13:15 UTC
Labels: typescript
