### ISSUE TITLE
Pool.prototype.query(sql, cb) error when getConnection failed

### ISSUE THREAD

**Issue by xingqiao** [sidorares/node-mysql2#311] opened 2016-05-15 08:49 UTC
node-mysql2 / lib / pool.js 
127 Pool.prototype.query = function (sql, values, cb) { 
128   var cmdQuery = Connection.createQuery(sql, values); 
129   this.getConnection(function (err, conn) { 
130     if (err) { 
131       return cb(err); 
132     } 

createQuery的参数需要加上 cb

getConnection失败时未检测cb类型，需要加上
147   if (typeof values === 'function') { 
148     cb = values; 
149     values = null; 
150   }

**Comment by sidorares** [comment] 2016-05-15 12:10
looks like this is duplicate of #270 . Please reopen if not

**Closed by sidorares** 2016-05-15 12:10 UTC
