### ISSUE TITLE
[BUG] Named placeholder breaking queries with strings containing ":"

### ISSUE THREAD

**Issue by damianobarbati** [sidorares/node-mysql2#1024] opened 2019-10-01 07:38 UTC
This:

```
const mysql = require('mysql2/promise');

(async () => {
    const pool = mysql.createPool({
        uri: '<conn string>',
        typeCast: true,
        timezone: 'local',
        namedPlaceholders: true,
    });

    const result = await pool.query(`select '{"handpicked":true}' as value`);
    console.log(result);
})();
```

Throws:
```
$ node test.js
/Users/damiano/Desktop/db-connection/node_modules/named-placeholders/index.js:95
      throw new Error('Named query contains placeholders, but parameters object is undefined');
      ^

Error: Named query contains placeholders, but parameters object is undefined
    at toArrayParams (/Users/damiano/Desktop/db-connection/node_modules/named-placeholders/index.js:95:13)
    at compile (/Users/damiano/Desktop/db-connection/node_modules/named-placeholders/index.js:144:12)
    at PoolConnection._resolveNamedPlaceholders (/Users/damiano/Desktop/db-connection/node_modules/mysql2/lib/connection.js:477:17)
    at PoolConnection.query (/Users/damiano/Desktop/db-connection/node_modules/mysql2/lib/connection.js:490:10)
    at /Users/damiano/Desktop/db-connection/node_modules/mysql2/lib/pool.js:145:12
    at /Users/damiano/Desktop/db-connection/node_modules/mysql2/lib/pool.js:63:16
    at PoolConnection.<anonymous> (/Users/damiano/Desktop/db-connection/node_modules/mysql2/lib/connection.js:718:13)
    at Object.onceWrapper (events.js:299:26)
    at PoolConnection.emit (events.js:209:13)
    at ClientHandshake.<anonymous> (/Users/damiano/Desktop/db-connection/node_modules/mysql2/lib/connection.js:105:14)
```

**Comment by damianobarbati** [comment] 2019-10-01 08:21
Also with the space before the separator:

```
const [[result]] = await pool.execute(`
    select
        '{"handpicked": true}' as value
    from
        jobs
    where
        now() >= :updated_at_from
`, { updated_at_from: '2019-09-20' });
```

Throws:
```
(node:4872) UnhandledPromiseRejectionWarning: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':updated_at_from' at line 1
    at PromisePool.execute (/Users/damiano/Desktop/db-connection/node_modules/mysql2/promise.js:343:22)
```

**Comment by damianobarbati** [comment] 2019-10-01 09:56
I'm having all these real-world bugs because I dropped sequelize which was handling the named placeholder logic and using mysql2 directly.

Other breaking scenario is a query having comments in it:

```
const [[result]] = await pool.execute(`select
    1, -- with namedPlaceholders=true, this comment breaks the query with the following tick '
    :ciao as value
`, { ciao: 'hello' });
```

```
const [[result]] = await pool.execute(`select
    1, -- this comment without the tick does not break
    :ciao as value
`, { ciao: 'hello' });
```

**Comment by sidorares** [comment] 2019-10-01 23:53
Thanks for report @damianobarbati 
Those type of bugs better be logged at https://github.com/mysqljs/named-placeholders/issues

Your first example seems like a duplicate of https://github.com/mysqljs/named-placeholders/issues/10 / https://github.com/sidorares/node-mysql2/issues/703

In general, if there an easy fix I'd be happy to see it implemented but "named-placeholders" library is scope similar to mysql.escape() / format() - make it easy to add placeholders to sql you write manually. It does not try to be full SQL parser and fully understand semantics of what is in the query, just a simple templating layer and not more

**Closed** 2019-10-27 10:05 UTC
