### ISSUE TITLE
How to connect to Google Cloud SQL with IAM and mysql_clear_password?

### ISSUE THREAD

**Issue by dloop-mb** [sidorares/node-mysql2#1782] opened 2023-01-12 14:50 UTC
I'm stuck with this problem and I have tried many things that were discussed here on the board but I can't make it work.

The scenario is the following:

- I have Google Cloud SDK running on my machine
- I have a Google Cloud SQL database (mysql)
- I have added a user as a database user via IAM (https://cloud.google.com/sql/docs/mysql/add-manage-iam-users)
- The user is logged in on my machine
- I should be able to login using the username and an access token as password (https://cloud.google.com/sql/docs/mysql/iam-logins)

I can connect to the database without problem using this command line on my machine:
```MYSQL_PWD=`gcloud sql generate-login-token` mysql --enable-cleartext-plugin --host=<public-ip> --user=<username>```

I configured SSL to not be required for the moment. The command also works with SSL. The command also works if I switch the "sql generate-login-token" to "auth print-access-token".

But I can't connect to the database using node-mysql2.
I have tried several things which I've found here on the board. E. g.:
```js
const auth = new GoogleAuth({
  ...,
  scopes: [ ..., 'https://www.googleapis.com/auth/sqlservice.login' ]
})
const password = (await auth.getAccessToken()) ?? undefined

const db = await mysql.createConnection({
  host: '<public-ip>',
  user: '<username>',
  password
})
await db.connect()
```

I have also tried with authPlugins, authSwitchHandler and with/without insecureAuth. But I always get the error:
`Access denied for user '<username>'@'<local-ip>' (using password: YES)`

Please can someone point out where I'm wrong?

**Comment by sidorares** [comment] 2023-01-12 23:09
Are you sure command line client is not using ssl? I'm keen to know if this is a bug in the library ( cleartext plugin or auth switch not working when ssl not enabled ) or just the server side behaviour. I'll try to replicate with the same steps

**Comment by sidorares** [comment] 2023-01-15 11:24
> Release Please creates a release pull request after it notices the default branch contains "releasable units" since the last release. A releasable unit is a commit to the branch with one of the following prefixes: "feat", "fix", and "deps". (A "chore" or "build" commit is not a releasable unit.)

Also this change should've been 3.1 release because its adding a new surface api ( users who depend on the library with this PR merged can't safely downgrade to 3.0 and this should be communicated by semver )

I'll try to push the release with next merged PR

**Comment by dloop-mb** [comment] 2023-01-16 07:31
I think your last comment was meant for a different issue.

To answer your previous question: Yes, I'm pretty sure the command is not using ssl if I don't specify the ssl parameters (--ssl-ca, --ssl-key and --ssl-cert). I'm also connecting to the database through dbeaver without ssl parameters.
Also, if I turn on "Allow only SSL connections." in Google Cloud SQL then the command stops working (without ssl, still works with ssl).

So I can connect to the database with and without ssl through command line, but with node-mysql2 I can only manage to connect using ssl.

**Comment by sidorares** [comment] 2023-01-16 07:51
haha, yes, meant to go here https://github.com/sidorares/node-mysql2/pull/1791

I have created instance on GCP and can replicate this behaviour locally. I'll try to trace mysql client behaviour with strace and / or wireshark, but I can confirm that when SSL is enabled cleartext auth is offered via auth switch and when there is no SSL auth switch command is not sent ( at least when connected via mysql2 driver ). Which kind of makes sense, but still unsure what causes this difference in behaviour

Also fyi - I do intend to require `enableCleartextAuthPlugin` flag in the future to avoid risk of accidentally connecting to a malicious server snd sending a password to it - see https://github.com/sidorares/node-mysql2/issues/1617

**Comment by dloop-mb** [comment] 2023-01-16 08:27
Maybe another interesting fact. If I create a database user with password (no IAM), then I can connect without ssl via node-mysql2.

**Comment by sidorares** [comment] 2023-01-16 09:49
> Maybe another interesting fact. If I create a database user with password (no IAM), then I can connect without ssl via node-mysql2.

It's likely using mysql_native_password or sha256 auth in that case

**Comment by sidorares** [comment] 2023-03-11 03:34
I haven't figured out yet exactly the difference between cli and mysql2, potentially its initial plugin used to connect ( mysql2 always using mysql_native_password and then can switch is server offer AUTH_SWITCH )

**Closed by sidorares** 2023-03-11 03:34 UTC
