### ISSUE TITLE
Error: Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by Rakeshvishnoi029** [sidorares/node-mysql2#939] opened 2019-03-29 05:29 UTC
Hi 

I fascing last 2 days this error please help me...

{ Error: read ETIMEDOUT
  at TCP.onread (net.js:622:25)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
    syscall: 'read',
 fatal: true }
 { Error: Can't add new command when connection is in closed state
   at PoolConnection._addCommandClosedState  

I use mysql 2 and connect Pool

var mysql = require('mysql2'); 
var mysqlPool = mysql.createPool({    
    host: 'localhost',
    user: 'root',
    password: 'xyz', 
    database: 'xyz',
    waitForConnections: true,
    connectionLimit: 10,
    queueLimit: 0
  }); 
 
module.exports = mysqlPool;

55|| { Error: read ETIMEDOUT
55||     at TCP.onread (net.js:622:25)
55||   errno: 'ETIMEDOUT',
55||   code: 'ETIMEDOUT',
55|    |   syscall: 'read',
55||   fatal: true }
55|| { Error: Can't add new command when connection is in closed state
55|     at PoolConnection._addCommandClosedState

**Comment by digiperfect-janak** [comment] 2019-04-04 08:29
+ 1 - we have been getting this issue since last yesterday. 

Error: This socket has been ended by the other party

followed by


Error: Can't add new command when connection is in closed state

**Comment by yunfan** [comment] 2019-04-14 15:18
we too :[

**Comment by zebullax** [comment] 2019-05-09 12:46
Same issue here

**Comment by Akash0333** [comment] 2019-05-14 15:41
Same issue here, please tell me how we can resolve it

**Comment by ovidiu-balau** [comment] 2019-07-12 14:40
Anyone found a fix for this?

**Comment by nag944** [comment] 2019-07-12 20:14
Any news on this problem ? After connection timed out, it cannot be restored at all - as all activity related to connection is performed in constructor. Also, this error is returned as text message only, no codes provided.

Is it safe just to recreate connection object ? Actually it's very pour idea, as connection instance is passed to many structures in the program...

**Comment by ovidiu-balau** [comment] 2019-07-30 12:41
Still an issue, anyone found any solution for this?

**Comment by jovemnf** [comment] 2019-08-02 18:49
me too

**Comment by coder77** [comment] 2019-08-12 05:11
I got this as well

**Comment by sidorares** [comment] 2019-08-12 05:14
Hey @coder77 @jovemnf @ovidiu-balau @Akash0333 @zebullax and everyone else experience issue - is there a reliable way to reproduce? Ideally dockerized self contained , or at least sequence of instructions

**Comment by nag944** [comment] 2019-08-12 06:20
> Hey @coder77 @jovemnf @ovidiu-balau @Akash0333 @zebullax and everyone else experience issue - is there a reliable way to reproduce? Ideally dockerized self contained , or at least sequence of instructions

It's extremely easy to reproduce - just start a connection and wait for default timeout (you can emulate it changing default mysql timeout setting to some smaller value - by default it's around 8 hours).

Btw, I tested it not on pool, but with raw connection - in this case error object is empty at all, only text message is present.

As I checked source code, seems this problem has no way to be solved in current state. When mysql connection is gone away, the network connection instance data inside the component is destroyed, so you cannot just restart the net - must create a new connection instance at all (network connection instance is created in the constructor !!!).

**Comment by sidorares** [comment] 2019-08-12 06:25
> As I checked source code, seems this problem has no way to be solved in current state.

Yes, individual `Connection` is not meant to survive underlying transport reconnect, it's 1:1 mapping to mysql connection / thread with same possible states ( authentication, change user, etc ). When network connection dies or actively closed by server it should not be re-used, this is just how it is designed. If it's your issue the solution should be in your code ( listen for `error` / `end` events etc ). If you want simpler api just use pool - it should handle all this

**Comment by nag944** [comment] 2019-08-12 06:29
But as I see previous messages, pool seems to have same problems ?

The only way I found is just send stub queries every hour to keep connection alive. In the other case, I cannot even make correct destruction - it hangs forever, so must forget about the instance and create new one - rely that garbage collector makes it's job right.

**Comment by zebullax** [comment] 2019-08-12 06:30
Unless I'm mistaken, issue is not limited to single connection but also connection managed by pool (that s what I was using as a setup), and that would make sense since the pool is only managing creating and yielding connection, if an existing connections has been remotely closed, and is yielded by the pool, we get the same error that if we were working with a simple connection

**Comment by sidorares** [comment] 2019-08-12 06:38
>  pool seems to have same problems ?

I'm happy to try to investigate, if I have simple way to reproduce with pool that would help me a lot

> if an existing connections has been remotely closed, and is yielded by the pool, we get the same error that if we were working with a simple connection

In the case of pool it's different in terms of who is responsible for tracking and recycling of dead connection. Pool should do it all for you while when you use individual connection you must listen for error ( both on connection and on query results )

**Comment by MR4online** [comment] 2019-08-14 12:57
having the same problem with pooled connections.
If our MySQL stats are correct, the count of the active connections does not vary over time. The last time the error occured was when an cron caused many queries. May be the aggregation of new connection doenst work as expected. Is there an way to debug that?

Our code looks pretty much like in the docs [https://github.com/mysqljs/mysql#pooling-connections](url). The most logic is simple (get new Connection from permanent Pool, query it, release it).

**Comment by ADumaine** [comment] 2019-08-30 01:01
I'm using a single connection and after the connection is lost con.end() or con.release() throws the error.
My current solution is to set the connection object to null and create a new connection on the error.

if (con) con=null
initcon();  //sets up the connection

**Comment by T1MOXA** [comment] 2019-10-05 20:56
I have the same problem

**Comment by Xsmael** [comment] 2019-10-21 11:59
Mee toO! any fix ?

**Comment by juaneuro90** [comment] 2019-10-21 13:25
Guys I'm having the same issue.

**Comment by jmordica** [comment] 2019-10-26 22:02
Me too.

**Comment by jmordica** [comment] 2019-10-27 03:47
Switching to createPool resolved my issue.

**Comment by franck-nadeau** [comment] 2020-01-10 21:19
> Switching to createPool resolved my issue.

@jmordica What do you mean by switching to createPool? That is what I am using and I am getting this problem. Also that is what Rakeshvishnoi029's initial code used. Are you passing something special as an option?

**Comment by zeeshanaligold** [comment] 2020-01-23 18:25
Hi @jmordica 

I have the same issue. Can you please tell how did you get it fix? Thx

```
const mysql = require('mysql2');

const con = mysql.createConnection({
    host     : process.env.RDS_HOSTNAME,
    user     : process.env.RDS_USERNAME,
    password : process.env.RDS_PASSWORD,
    database : process.env.RDS_DATABASE
});

```

**Comment by coplayer** [comment] 2020-04-02 05:09
i have same issue solve plz

**Comment by rudiantotiofan** [comment] 2020-04-03 20:29
any update for this issue ? i got the same problem.

Thanks,

**Comment by davehorton** [comment] 2020-04-07 13:45
Same issue here, using createPool.  Any updates on this?
```
const pool = mysql.createPool({
  host: process.env.XX,
  user: process.env.XXX,
  password: process.env.XX,
  database: process.env.XX,
  connectionLimit: process.env.XX
});
```

```
"err":
{"type":"Error","message":"Can't add new command when connection is in closed state","stack":"Error: Can't add new command when connection is in closed state\n    
at PoolConnection._addCommandClosedState (/../mysql2/lib/connection.js:137:17)\n    
at PoolConnection.query (../mysql2/lib/connection.js:502:17)\n    
at getMysqlConnection (../login.js:31:10)\n    
at process.nextTick (../mysql2/lib/pool.js:44:37)\n    
at process._tickCallback (internal/process/next_tick.js:61:11)","fatal":true},"msg":"Error getting db connection","v":1
```

at least update the docs to remove the misleading information that pool handles this for you.

**Comment by sidorares** [comment] 2020-04-07 14:19
@davehorton unfortunately not enough information to debug. Can you make a test repo to reproduce?

This can happen if you call `.end()` on connection and later try to call `.execute()` this might be a logic error in your application but could be a bug in the driver, unfortunately not enough information to tell

**Comment by runekm** [comment] 2020-05-01 09:48
I too get this error from time to time. I haven't investigated the problem in detail, but it seems to occur every couple of days, and lasts untill the app is restarted.

The connection pool is created with:
`var mysql = require('mysql2');
pool = mysql.createPool({
	connectionLimit : config.DB_CONNECTION_LIMIT,
	host     		: config.DB_HOST,
	port     		: config.DB_PORT,
	user     		: config.DB_USER,
	password 		: config.DB_PASSWORD,
	database 		: config.DB_DATABASE,
	dateStrings		: true,
	debug			: config.DB_DEBUG
});
promisePool = pool.promise();`

The error occurs when I run:
`[ results, fields ] = await connection.query( sql );`
after running:
`connection = await promisePool.getConnection();`
which gives no error.

The error says:
`Error: Can't add new command when connection is in closed state
at PromisePoolConnection.query ([path_to_my_app]/node_modules/mysql2/promise.js:92:22`

**Comment by d3rf** [comment] 2020-06-15 22:41
I solved in a class like doing something like that. 

`class MySQLExec {
    //propriedades e funções da classe aqui
    constructor() {
     
    }
    conecta(){
      this.conn =  mysql.createConnection({
        host: '',
        user: '',
        database: '',
        password:config.password,
        multipleStatements: true
       // waitForConnections: true
      });  
    }
    run(query,rows) {
        var returnResult = null;
       //connect
        this.conecta();
        this.conn.query(
            query,
            rows,
            function(err, results, fields) {
              returnResult = results;              
             // results contains rows returned by server
            
             if (err){
               console.error(err)
             }

             // console.log(fields); // fields contains extra meta data about results, if available
             // return results;
              // If you execute same statement again, it will be picked from a LRU cache
              // which will save query preparation time and give better performance
              //
            }
          );
         //disconnect after run
          this.conn.end();
          //this.conn.end();
          return returnResult; 
    }
}`

**Comment by skorolev-tjc** [comment] 2020-06-29 11:04
I had the same issue with pooled connections and 8.0.15 server and to make things worse I had also long running connections. For now I have a cautious optimism that the issue is resolved. Some changes must be done in your logic:

1. If you need long running connections then first check MySQL server parameter **wait_timeout** - it is in seconds and it will kill silent connections after the period of time, probably it will be sufficient for you just to increase this value
2. If wait_timeout is not sufficient you can use **connection.ping** method with some interval - it will keep the connection alive
3. Do analyse error object after operations: if it has **fatal = true** then the connection became useless (probably it was closed somehow or connection was lost) - you must call **connection.destroy()** - it will remove this poisoned connection from the pool otherwise the pool can provide this connection again – probably  some change should be implemented in the pool logic.

**Comment by gaurav16694** [comment] 2020-10-07 05:19
is there any update on this issue either how to reproduce it or fix it ?

**Comment by HsinHeng** [comment] 2020-10-23 06:46
In my case, I perform insertMany exceed 30,000 records at one time.
The error was produced.

I resolved my issue by increase `max_allowed_packet` in mysql server config.
because the transmission bytes are too large.

**Comment by sidorares** [comment] 2020-10-23 07:16
@HsinHeng interesting, maybe that can be solved at driver level. We should be able to automatically detect `max_allowed_packet` ( from settings or by querying variable immediately after connection ) and then splitting outgoing packet into smaller packets - see https://dev.mysql.com/doc/internals/en/sending-more-than-16mbyte.html

mysql2 does support large incoming packet sizes ( see https://github.com/sidorares/node-mysql2/blob/442d3042245c761eaeafe36b0e35d45cb3f87025/lib/packet_parser.js#L83-L97 ) but your issue is probably related to packet length > max_allowed_packet and not 16Mbyte packets. I need to double check maybe `max_allowed_packet` can be automatically sent at connection but if not still can be queried using `.query()`

**Comment by sidorares** [comment] 2020-10-23 07:26
@HsinHeng what was exactly error code in your case? Having some help in error message would be useful I guess. Something along the lines `if(error.code === errors.ER_NET_PACKET_TOO_LARGE) { error.message = "Packet too large. Check max_allowed_packet system/session variable. See [wiki url with more info] for more information" }`

**Comment by HsinHeng** [comment] 2020-10-23 08:47
> @HsinHeng what was exactly error code in your case? Having some help in error message would be useful I guess. Something along the lines `if(error.code === errors.ER_NET_PACKET_TOO_LARGE) { error.message = "Packet too large. Check max_allowed_packet system/session variable. See [wiki url with more info] for more information" }`

@sidorares 
You are got it!

Here is my error details.

"name":"SequelizeDatabaseError","parent":{"code":"ER_NET_PACKET_TOO_LARGE","errno":1153,"sqlState":"08S01","sqlMessage":"Got a packet bigger than 'max_allowed_packet' bytes" }

Hope can you resolve this issue.

**Comment by sidorares** [comment] 2020-10-23 08:56
@HsinHeng well in your case error text from the server already had some hints

What we can do is have `maxAllowedPacketSize` connection option that maybe is "auto" by default. When set to auto a query is performed immediately on connection to get `max_allowed_packet` variable ( downside: slightly worse latency until first "useful" response, especially when connection is always shoer lived )

**Comment by greedThread** [comment] 2021-03-11 02:09
Still an issue, anyone found any solution for this?

**Comment by MrBargz** [comment] 2021-04-09 23:55
the same problem

**Comment by Desnoo** [comment] 2021-04-14 07:59
We also have this issue, when the connections in the connection pool are long in idle mode.
I debugged to the getConnection point and printed out the connection state that is returned at https://github.com/sidorares/node-mysql2/blob/07a429d9765dcbb24af4264654e973847236e0de/lib/pool.js#L45

The contents of the connection are as follows:
```
  1: connection =
    { _events: Object,
      _eventsCount: 1,
      _maxListeners: 'undefined',
      config: ConnectionConfig,
      stream: Socket,
      ... }
  2: connection._fatalError =
    { errno: 'ECONNRESET',
      code: 'ECONNRESET',
      syscall: 'read',
      fatal: true,
      stack: 'Error: read ECONNRESET\n' +
      '    at TCP.onStreamRead [as…tic-apm-node/lib/instrumentation/index.js:328:27)',
      ... }
  3: connection._protocolError =
    { fatal: true,
      code: 'PROTOCOL_CONNECTION_LOST',
      stack: 'Error: Connection lost: The server closed the conn…js:483:12)\n' +
      '    at TCP.<anonymous> (net.js:675:12)',
      message: 'Connection lost: The server closed the connection.',
      Symbol(callsites): Array(4) }
  4: connection._statements =
    { Symbol(max): 16000,
      Symbol(lengthCalculator): ,
      Symbol(allowStale): false,
      Symbol(maxAge): 0,
      Symbol(dispose): ,
      ... }
  5: connection._internalId = 3
```
So the error seems to come in effect when the mysql server closes the connection "Connection lost: The server closed the connection.". Do you have any hints to prevent this?

**Comment by JonHX** [comment] 2021-06-08 11:14
Same issue here

**Comment by SouzaCarleone** [comment] 2021-08-20 14:05
Error: Can't add new command when connection is in closed state

Same issue here, any suggestion ?

**Comment by yo-wan** [comment] 2021-08-23 08:56
Possible workaround could be to check if any of connection's properties _fatalError, _protocolError, _closing is true before executing the query and to get new connection. But that is ugly and looking for better solution, probably based on events.

**Comment by irepela** [comment] 2021-09-08 13:33
I solved this problem by refactoring my code to use pool.query (which releases connection internally) instead of using connection.query and releasing connection manually. Looks like there was a connection leak in my code.

**Comment by MaksemM** [comment] 2021-09-13 22:34
> I solved this problem by refactoring my code to use pool.query (which releases connection internally) instead of using connection.query and releasing connection manually. Looks like there was a connection leak in my code.

Do you have an example?

**Comment by irepela** [comment] 2021-09-14 06:52
It didn't happen again in my case. Here is an example what was change:

Old code:
  let connection;
  try {
    connection = await pool.getConnection();
    const [rows] = await connection.query(SELECT_USERS, [id]);
    return res.send(rows);
  } catch (sqlError) {
    await handleError(res, sqlError);
  } finally {
    await connection.release();
  }
  
  New code:
   try {
    const [rows] = await pool.query(SELECT_USERS, [id]);
    return res.send(rows);
  } catch (sqlError) {
    await handleError(res, sqlError);
  }

**Comment by ChromeUniverse** [comment] 2021-09-27 02:24
> It didn't happen again in my case. Here is an example what was change:
> 
> Old code:
> let connection;
> try {
> connection = await pool.getConnection();
> const [rows] = await connection.query(SELECT_USERS, [id]);
> return res.send(rows);
> } catch (sqlError) {
> await handleError(res, sqlError);
> } finally {
> await connection.release();
> }
> 
> New code:
> try {
> const [rows] = await pool.query(SELECT_USERS, [id]);
> return res.send(rows);
> } catch (sqlError) {
> await handleError(res, sqlError);
> }

Has anyone else been able to confirm that this works or found other fixes? I'll try refactoring my code anyways to test this out, but I would love to get more information if possible.

I'm currently using mysql2's promise API to create the connection but also getting the same error:

` ` ` 
// connect to MySQL database
async function sql_connect() {
  // connect to database
  db = await mysql.createConnection({
    host     : 'localhost',
    user     : 'lucca',
    password : process.env.MYSQL_PASSWORD, 
    database : 'tank_battle'
  });

  return db;
}
` ` `

**Comment by MaksemM** [comment] 2021-09-27 02:43
> It didn't happen again in my case. Here is an example what was change:
> 
> Old code:
> let connection;
> try {
> connection = await pool.getConnection();
> const [rows] = await connection.query(SELECT_USERS, [id]);
> return res.send(rows);
> } catch (sqlError) {
> await handleError(res, sqlError);
> } finally {
> await connection.release();
> }
> 
> New code:
> try {
> const [rows] = await pool.query(SELECT_USERS, [id]);
> return res.send(rows);
> } catch (sqlError) {
> await handleError(res, sqlError);
> }

Thanks for that. I changed my code to use promise pool and it seems to have resolved itself, but I'm still cautious. Thanks for showing me the snippet.

**Comment by MaksemM** [comment] 2021-09-27 02:50
> > It didn't happen again in my case. Here is an example what was change:
> > Old code:
> > let connection;
> > try {
> > connection = await pool.getConnection();
> > const [rows] = await connection.query(SELECT_USERS, [id]);
> > return res.send(rows);
> > } catch (sqlError) {
> > await handleError(res, sqlError);
> > } finally {
> > await connection.release();
> > }
> > New code:
> > try {
> > const [rows] = await pool.query(SELECT_USERS, [id]);
> > return res.send(rows);
> > } catch (sqlError) {
> > await handleError(res, sqlError);
> > }
> 
> Has anyone else been able to confirm that this works or found other fixes? I'll try refactoring my code anyways to test this out, but I would love to get more information if possible.
> 
> I'm currently using mysql2's promise API to create the connection but also getting the same error:
> 
> ```js
> // connect to MySQL database
> async function sql_connect() {
>   // connect to database
>   db = await mysql.createConnection({
>     host     : 'localhost',
>     user     : 'lucca',
>     password : process.env.MYSQL_PASSWORD, 
>     database : 'tank_battle'
>   });
> 
>   return db;
> }
> ```

I'll show you what is currently working for me:

**Database file:**

`require('dotenv').config()
const mysql = require('mysql2')

module.exports =  mysql.createPool({
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  timezone: 'Australia/Sydney',
  waitForConnections: true,
  connectionLimit: 10,
  queueLimit: 0,
  debug: false
})`

**Controller file snippet**

`const pool = require('../models/db/db')
const promisePool = pool.promise()

createSalesOrderPost: async (req, res) => {
        const page_path = '/admin/sales-orders/edit-order?clientid=' + req.body.clientid
        try {

            if (req.file) {
                var xmlfile = req.file.originalname
            }

            // Database details
            const sql_1 = 'INSERT INTO mt_sales_orders (client_id, payment_id, sales_order_amount, xml_order) VALUES (' + req.body.clientid + ', ' + req.body.paymentid + ', ' + req.body.paymentamount + ', "' + xmlfile + '");'

            const [rows1, fields1] = await promisePool.query(sql_1)

            const sql_2 = 'UPDATE mt_payments SET sales_order_id= (SELECT sales_order_id FROM mt_sales_orders WHERE payment_id=' + req.body.paymentid + ') WHERE payment_id=' + req.body.paymentid

            // Create database entry
            const [rows2, fields2] = await promisePool.query(sql_2)

            await req.flash($success_msg, 'XML Order added successfully.')
            res.redirect(page_path)            

        } catch (error) {
            await req.flash($error_msg, 'Something went wrong.' + ' ' + error)
        }
    }`

I haven't had any issues ever in my local environment and the issue seems to have fixed on live server.

Project is still in development so when I update live server with finished program I'll update if there is an issue.

**Comment by ishmum123** [comment] 2021-09-29 14:05
The socket it internally uses, has a `destroyed` property. I was thinking of accessing that and reconnecting when a new query comes in. Please suggest if there's something better than this. Alternatively you guys could expose the property.

**Comment by ChromeUniverse** [comment] 2021-10-01 19:10
Thanks for the tips, @irepela and @MaksemM! I'm refactoring my code now to use connection pooling/pool queries with promises. Hoping for the best.

**Comment by ChromeUniverse** [comment] 2021-10-02 12:58
Update: it works! 

Async/await connection pooling seems to have done the trick. My server has been running for about 17 hours now without throwing any errors. If anyone's still having any issues, I suggest following **irepela** and **MaksemM**'s example. My current setup is described below:

First, you create a connection pool with `mysql2/promise` and export it for reuse across different modules.

* `sql_util.js` - creates connection pool: 
```js
// package imports
const mysql = require('mysql2/promise');
require('dotenv').config();

// exporting MySQL connection pool object
module.exports = mysql.createPool({
  host: 'localhost',
  user: 'lucca',
  password: process.env.MYSQL_PASSWORD,
  database: 'tank_battle',
  waitForConnections: true,
  connectionLimit: 20,
  queueLimit: 0
})
```

Then, in your main file/routes/middleware/APIs/whatever, you just need to import the `pool` object and run your query on the `pool` object just as you would with a regular MySQL connection object. In other words, use `await pool.query` instead of `await connection.execute` or `await connection.query`. 

* `api.js` - internal app logic for handling API requests:
```js
const { private } = require('../middleware/private');   // -> custom middleware for private routes
const pool = require('../sql_util');                    // -> creates connection pool (see above) 
const jwt = require("jsonwebtoken");                    // -> "jsonwebtoken" package from npm

// Express Router setup
const router = express.Router();
router.use(private);

// GET /user    --> returns user information
router.get('/user', async (req, res) => {

  const decoded = jwt.decode(req.token, {complete: true});
  const name = decoded.payload.username.toString();

  const sql = "select username, elo, lb_rank, tank_color from users where username=?"

  try {
    const [query_result, fields, err] = await pool.query(sql, [name]);

    if (query_result.length > 0) {

      const q = query_result[0]

      // BinaryRow {
      //   username: 'Lucca',
      //   elo: 1000,
      //   lb_rank: 1,
      //   tank_color: #12fca7
      // }

      const userData = {
        error: false,
        name: q.username,
        elo: q.elo,
        lb_rank: q.lb_rank,
        tank_color: q.tank_color
      }

      res.status(200);
      res.json(userData);
      return;

    } else {
      console.log('user not found');

      res.status(404);
      res.json({
        error: true,
        message: 'User not found'
      });

      return;
    }

  }

  catch (e) {
    res.status(500);
    res.json({
      error: true,
      message: 'Server Error'
    });
    console.log(e);
    return;
  }

});

module.exports = router;
```

**Comment by Nedudi** [comment] 2021-10-14 22:02
I am having the same issue (mysql 8 and knex.js with pool of connections)

**Comment by OpakAlex** [comment] 2021-12-08 13:29
2 years, no solution, amazing why people still use this library?))))

**Comment by ChromeUniverse** [comment] 2021-12-08 15:29
> 2 years, no solution, amazing why people still use this library?))))

Many people have already provided their own solutions on this issue thread, and most of them appear to work just fine. Could you at least read through a couple of them?

**Comment by OpakAlex** [comment] 2021-12-08 15:58
yes, copy/paste the best solution, since 1950 ;) i think we did some progress at 2021, but looks like no))) Good i will copy paste code as all world.

**Comment by ChromeUniverse** [comment] 2021-12-09 00:47
> Alex

????????

\<rant>
Look, here's my point: no, this issue hasn't gone without any solutions for two years, people have already solved this problem before as detailed in previous comments (including the ones I made a couple of months ago) - but God forbid actually taking some time to read any of those, right? 

Now, If you're so keen on figuring out stuff on your own, then by all means, feel free to keep banging your head on your keyboard while you sift through the meh-ish docs. Alternatively, you could save some time and frustration and take advantage of the work that the kind folks here have done for you by detailing their solutions to this, frankly, very dumb problem. Honestly, you won't be gaining much by *not* copying and pasting code from this thread.

Since this discussion is incredibly unproductive, I'll shut up now. Sorry.
\</rant>

**Comment by sidorares** [comment] 2021-12-09 02:15
While I don't have a good actual answer there are some useful proposals. If anyone wants to help to contribute there are some good ways do do so:

- reliable way to reproduce so local debugging is easy. Good examples: 1) a docker image with everything ready ( including server ), 2) repro repo with code and documentation for external dependencies
- a PR with reliable failing test

Closing the issue and locking comments, looks like discussion here does not add much value. =

**Closed by sidorares** 2021-12-09 02:15 UTC
