### ISSUE TITLE
Sequelize broken with v2.3.1

### ISSUE THREAD

**Issue by ddolcimascolo** [sidorares/node-mysql2#1418] opened 2021-10-15 15:08 UTC
Hello,

Long-time user of sequelize + mysql2 here.
Our build starts to fail when upgrading to v2.3.1 of your library. I didn't investigate deeply yet but the error we're getting is

```
SequelizeDatabaseError: Cannot read property 'parse' of undefined
  at Query.formatError (node_modules/sequelize/lib/dialects/mysql/query.js:265:16)
  at Query.run (node_modules/sequelize/lib/dialects/mysql/query.js:77:18)
```

I can also open an issue there if you feel the issue is on their side, but you released a _minor_ version wich isn't supposed to contain breaking changes.

I can provide logs, reproduction repo, anything you'd need to debug.

Cheers,
David

**Comment by rnkhouse** [comment] 2021-10-15 18:08
It's breaking with the 2.3.1 version. The error we get is: `uncaughtException: The value of "offset" is out of range. It must be >= 0 and <= 1248. Received 1252`

**Comment by edgedemon** [comment] 2021-10-15 19:09
sequelize is broken with version 2.3.1 not with 2.3.0.

the problem comes from this file:
https://github.com/sidorares/node-mysql2/blob/master/lib/parsers/text_parser.js
you are using readCodeFor which applies JSON.parse 
![image](https://user-images.githubusercontent.com/5783253/137540036-5f048c82-cead-4600-998f-88c67c40a055.png)
and then assigning that to _this which ends with 
![image](https://user-images.githubusercontent.com/5783253/137539897-127f052d-2160-4259-b557-afb62a73d2b0.png)
_this.JSON.parse(packet.readLengthCodedString("utf8"))
instead of 
JSON.parse(_this.packet.readLengthCodedString("utf8"))
![image](https://user-images.githubusercontent.com/5783253/137540115-f908dc89-7322-42e0-82c2-bd891566b8ce.png)

**Comment by sidorares** [comment] 2021-10-15 22:45
@testn looks like #1402 is causing this regression ( typeCast + JSON field )

**Comment by sidorares** [comment] 2021-10-15 23:28
my attempt to fix: #1420 
cc @testn @edgedemon @ddolcimascolo

**Comment by testn** [comment] 2021-10-15 23:49
@sidorares sorry I must have missed a case with JSON.

**Comment by sidorares** [comment] 2021-10-15 23:51
@testn I'm a bit worried about `uncaughtException: The value of "offset" is out of range. It must be >= 0 and <= 1248. Received 1252` - could it be we are reading data from wrong packet reference?

**Comment by testn** [comment] 2021-10-15 23:55
Let me take a look.

**Comment by testn** [comment] 2021-10-16 00:12
Your fix is reasonable. @sidorares where do you see `uncaughtException: The value of "offset" is out of range. It must be >= 0 and <= 1248. Received 1252`?

**Comment by testn** [comment] 2021-10-16 01:32
@mkhouse Do you have a repro?

**Comment by ddolcimascolo** [comment] 2021-10-16 07:54
@sidorares Fixed! Thx for your help

**Comment by edgedemon** [comment] 2021-10-16 12:52
@sidorares the only issue i see with your code is you are duplicating the memory used for reading each package since you are asigning another variable and passing the whole content to it, each time for each package of each field, and that doesnt sit well with me.

`_this.JSON.parse(...` 
is exactly the issue

im pretty sure my code in the line 126, would translate to this which is 
`JSON.parse(_this.packet` 


the issue would be on line 134 where you have this

`parserFn(`${lvalue} = ${readCode};`);`

but it would be easier to change this line too, to
`parserFn(`${lvalue} = JSON.parse(${readCode});`);`

changes a single line over my previous commit, maintain functionality and doesn't waste memory.

**Comment by edgedemon** [comment] 2021-10-16 13:05
easier yet add an optional parameter on the readCodeFor function with default true and set to false in the call of the line 126
i did it here https://github.com/edgedemon/node-mysql2/blob/fix/json-parsing-read-next/lib/parsers/text_parser.js

im making one extra if check at generation time for JSON type only, and saving memory over the acepted answer

**Comment by testn** [comment] 2021-11-10 04:17
@sidorares  let's close this?

**Closed** 2021-11-10 04:48 UTC
